### ISSUE TITLE
 URI::InvalidURIError in Home#index 

### ISSUE THREAD

**Issue by tnedich** [bigardone/rails_and_flux#2]
Getting this error:

 URI::InvalidURIError in Home#index 

Showing d:/Web projekti/RAILS/rails_and_flux/app/views/layouts/application.html.haml where line #7 raised:

bad URI(is not URI?): file-digest://d:/Web projekti/RAILS/rails_and_flux/config/routes.rb
Rails.root: d:/Web projekti/RAILS/rails_and_flux

Can it be spaces in folder name

OS: Win7

**Comment by tnedich** [comment]
Path contained spaces d:/Web projekti/RAILS/rails_and_flux and that caused problem.

**Comment by phyominhtun** [comment]
I'm having same problem.. Can you help me out ?
